// Generated by CoffeeScript 1.6.3
(function() {
  Template.sliderItem.helpers({
    image: function() {
      return "/images/" + this.img;
    },
    caption: function() {
      return this.caption;
    }
  });

}).call(this);
