// Generated by CoffeeScript 1.6.3
(function() {
  Template.slider.renderDelayWait = false;

  Template.slider.iosSliderPreset = false;

  Template.slider.rendered = function() {
    if (!Template.slider.renderDelayWait) {
      Template.slider.renderDelayWait = true;
      console.log(typeof launchSlider);
      Meteor.setTimeout(launchSlider, 500);
    } else {
      console.log("skipped iosSlider");
    }
    return false;
  };

  Template.slider.helpers({
    sliderItems: function() {
      var tt;
      return tt = ["four", "three"];
    }
  });

}).call(this);
