// Generated by CoffeeScript 1.6.3
(function() {
  this.slideComplete = function(args) {
    if (!args.slideChanged) {
      return false;
    }
    $(args.sliderObject).find('.text1, .text2').attr('style', '');
    $(args.currentSlideObject).find('.text1').animate({
      right: '200px',
      opacity: '0.8'
    }, 401, 'easeOutQuint');
    $(args.currentSlideObject).find('.text2').animate({
      right: '50px',
      opacity: '0.8'
    }, 1801, 'easeOutQuint');
    return false;
  };

  this.slideChange = function(args) {
    var n;
    n = args.currentSlideNumber - 1;
    $('.sliderContainer .slideSelectors .item').removeClass('selected');
    $('.sliderContainer .slideSelectors .item:eq(' + n + ')').addClass('selected');
    return false;
  };

  this.sliderLoaded = function(args) {
    $(args.sliderObject).find('.text1, .text2').attr('style', '');
    $(args.currentSlideObject).find('.text1').animate({
      right: '200px',
      opacity: '0.8'
    }, 400, 'easeOutQuint');
    $(args.currentSlideObject).find('.text2').delay(200).animate({
      right: '50px',
      opacity: '0.8'
    }, 400, 'easeOutQuint');
    slideChange(args);
    return false;
  };

  this.launchSlider = function() {
    if (Template.slider.iosSliderPreset === true) {
      $('.iosSlider').iosSlider('destroy');
    }
    $('.iosSlider').iosSlider({
      snapToChildren: true,
      desktopClickDrag: true,
      infiniteSlider: true,
      navSlideSelector: '.sliderContainer .slideSelectors .item',
      keyboardControls: true,
      onSlideComplete: slideComplete,
      onSliderLoaded: sliderLoaded,
      onSlideChange: slideChange,
      autoSlide: true,
      scrollbar: true,
      scrollbarContainer: '.sliderContainer .scrollbarContainer',
      navPrevSelector: '.prevButton',
      navNextSelector: '.nextButton'
    });
    Template.slider.iosSliderPreset = true;
    return Template.slider.renderDelayWait = false;
  };

}).call(this);
